//------------------------------------------------------------------------------
// Item.CS
// Author: Ethan Bartel
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Item class
/// </summary>
public class Item
{
    /// <summary>
    /// string holding the name of the Item
    /// </summary>
    public string name;

    /// <summary>
    /// price of the Item
    /// </summary>
    public decimal price;

    /// <summary>
    /// Constructor for a new Item
    /// </summary>
    /// <param name="n">name of item</param>
    /// <param name="p">price of item</param>
    public Item(string n, Decimal p)
    {
        name = n;
        price = p;
    }

}

