//------------------------------------------------------------------------------
// Rebate.CS
// Author: Ethan Bartel
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Rebate Class holds Transaction ids of transactions that sent in rebates and relevant rebate information
/// </summary>
public class Rebate
{
    /// <summary>
    /// id of transaction for the rebate
    /// </summary>
    public int id;

    /// <summary>
    /// name of the customer
    /// </summary>
    public string name;

    /// <summary>
    /// address of the customer
    /// </summary>
    public string address;

    /// <summary>
    /// constructor for the new rebate
    /// </summary>
    /// <param name="i">id of the transaction</param>
    /// <param name="n">name of customer</param>
    /// <param name="a">address of customer</param>
    public Rebate(int i, string n, string a)
    {
        id = i;
        name = n;
        address = a;
    }

}

