//------------------------------------------------------------------------------
// RebateCheck.CS
// Author: Ethan Bartel
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// RebateCheck class represents a rebate check to be sent out to a customer
/// </summary>
public class RebateCheck
{
    /// <summary>
    /// name of customer
    /// </summary>
    private string name;
	
    /// <summary>
    /// address of customer
    /// </summary>
    private string address;

    /// <summary>
    /// amount the rebate check is for
    /// </summary>
    private decimal amount;

    /// <summary>
    /// constructor for new RebateCheck
    /// </summary>
    /// <param name="n">name of customer</param>
    /// <param name="a">address of customer</param>
    /// <param name="amnt">amount of money the check is for</param>
    public RebateCheck(string n, string a, decimal amnt)
    {
        name = n;
        address = a;
        amount = amnt;
    }

}

