//------------------------------------------------------------------------------
// TransactionDB.CS
// Author: Ethan Bartel
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

/// <summary>
/// Transaction Database for holding and manipulating our Dictionary of transactions
/// </summary>
public class TransactionDB
{
    public Dictionary<int, SalesTransaction> Transactions = new Dictionary<int, SalesTransaction>();
   

}

